# Database Configuration for Production
spring.datasource.url=jdbc:postgresql://${PGHOST:kamann.up.railway.app}:5432/${PGDATABASE:railway}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA settings for Production
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Connection pool settings for Production
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Server configuration
server.port=${SERVER_PORT}
app.dataseed.enabled=false
server.ssl.enabled=false

# Application URLs
confirmation.link=${CONFIRMATION_LINK_PROD}
reset.password.link=${RESET_PASSWORD_LINK_PROD}