# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Docker Compose Configuration
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose-dev.yml

# Optional JPA settings
spring.jpa.hibernate.ddl-auto=create-drop

# SERVER CONFIGURATION
spring.application.name=kamann
server.port=8081

# HEALTHCHECK
management.endpoints.web.base-path=/actuator

# SCHEDULER
scheduler.occurrence.until-months=2

# CONFIRMATION LINK
confirmation.link=${CONFIRMATION_LINK}
reset.password.link=${RESET_PASSWORD_LINK}