spring.profiles.active=dev

# Application
app.base-url=http://localhost:8080

# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SWAGGER
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.tagsSorter=alpha

# JWT CONFIGURATION
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_TIME}

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# DEBUG entity scanning and JPA mapping
logging.level.org.hibernate.metamodel.model.domain=DEBUG
logging.level.org.hibernate.orm.boot.internal.MetadataBuilderImpl=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.data.jpa.repository.config=DEBUG

# Optional: enforce entity scanning failures
spring.jpa.properties.hibernate.archive.autodetection=class,hbm