package pl.kamann.config.codes;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum AuthCodes {
    UNAUTHORIZED("UNAUTHORIZED"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    INVALID_TOKEN("INVALID_TOKEN"),
    RESET_PASSWORD_EMAIL_ERROR("RESET_PASSWORD_EMAIL_ERROR"),
    CONFIRMATION_EMAIL_ERROR("CONFIRMATION_EMAIL_ERROR"),
    EMAIL_NOT_CONFIRMED("EMAIL_NOT_CONFIRMED"),
    USER_NOT_ACTIVE("USER_NOT_ACTIVE"),
    USER_ALREADY_CONFIRMED("USER_ALREADY_CONFIRMED");

    private final String code;
}
