package pl.kamann.application;

public enum AuthCode {
    USER_NOT_FOUND,
    INVALID_TOKEN,
    ALREADY_CONFIRMED, EMAIL_NOT_CONFIRMED, INVALID_PASSWORD, INVALID_CREDENTIALS, ACCOUNT_DELETION_FAILED
}