name: Build and Test Application

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Docker
        run: |
          docker --version
          docker ps

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker is Running
        run: docker info

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Run Tests with Testcontainers
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:tc:postgresql:16:///testdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.testcontainers.jdbc.ContainerDatabaseDriver
          JWT_SECRET: test-secret-key-for-github-actions
          JWT_EXPIRATION_TIME: 86400000
          MAIL_USERNAME: test@example.com
          MAIL_PASSWORD: test-password
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          SERVER_PORT: 8080
        run: mvn test

      - name: Print Test Logs (if failure)
        if: failure()
        run: cat target/surefire-reports/*.txt