name: Build and Test with H2 Database

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "SPRING_TEST_CONTEXT_FAILURE_THRESHOLD=5" >> $GITHUB_ENV

      - name: Build and test with Maven
        run: mvn -B test

      - name: Print test logs on failure
        if: failure()
        run: find target/surefire-reports -name "*.txt" -exec cat {} \;
