name: Build and Test Application

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Docker Compose
        run: |
         sudo apt-get update
         sudo apt-get install -y docker-compose

      - name: Build Application
        run: mvn clean package

      - name: Print Docker Logs
        if: always()
        run: docker-compose logs

      - name: Start Docker Containers with GitHub Secrets
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SPRING_RABBITMQ_HOST: ${{ secrets.SPRING_RABBITMQ_HOST }}
          SPRING_RABBITMQ_PORT: ${{ secrets.SPRING_RABBITMQ_PORT }}
          RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          MEMBERSHIPCARD_HISTORY_EXCHANGE: ${{ secrets.MEMBERSHIPCARD_HISTORY_EXCHANGE }}
          MEMBERSHIPCARD_HISTORY_QUEUE: ${{ secrets.MEMBERSHIPCARD_HISTORY_QUEUE }}
          MEMBERSHIPCARD_HISTORY_ROUTINGKEY: ${{ secrets.MEMBERSHIPCARD_HISTORY_ROUTINGKEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          docker-compose up -d --build
          sleep 45


      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
