name: Build and Test with Testcontainers

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Enable Docker container reuse
        run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      - name: Set up Testcontainers environment
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_CHECKS_DISABLE: true
          DOCKER_HOST: unix:///var/run/docker.sock

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
          JWT_SECRET: tSGVsbG8gV29ybGQ=
          JWT_EXPIRATION_TIME: 86400000
          SPRING_TEST_CONTEXT_FAILURE_THRESHOLD: 5
        run: mvn -B test -X

      - name: Print test logs on failure
        if: failure()
        run: find target/surefire-reports -name "*.txt" -exec cat {} \;
