name: Build and Test with H2 Database

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          CONFIRMATION_LINK: ${{ secrets.CONFIRMATION_LINK }}
          RESET_PASSWORD_LINK: ${{ secrets.RESET_PASSWORD_LINK }}
          SPRING_TEST_CONTEXT_FAILURE_THRESHOLD: 5
        run: mvn -B test

      - name: Print test logs on failure
        if: failure()
        run: find target/surefire-reports -name "*.txt" -exec cat {} \;
