name: Build and Test with Testcontainers

on:
#  pull_request:
#    branches: [ master, test-actions]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - name: Pull PostgreSQL image for Testcontainers
#        run: docker pull postgres:16

      - name: Build and test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
          JWT_SECRET: tSGVsbG8gV29ybGQ=
          JWT_EXPIRATION_TIME: 86400000
          SPRING_TEST_CONTEXT_FAILURE_THRESHOLD: 5
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_CHECKS_DISABLE: true
        run: mvn -B test

      - name: Print test logs on failure
        if: failure()
        run: find target/surefire-reports -name "*.txt" -exec cat {} \;
